# =========================
# BUILD STAGE
# =========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

# Copy only project first for better layer caching
COPY src/Vault.Dummy.Web/Vault.Dummy.Web.csproj ./Vault.Dummy.Web/
RUN dotnet restore ./Vault.Dummy.Web/Vault.Dummy.Web.csproj

# Copy rest of the source
COPY src/Vault.Dummy.Web/ ./Vault.Dummy.Web/

# Publish
RUN dotnet publish ./Vault.Dummy.Web/Vault.Dummy.Web.csproj \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false \
    /p:ContinuousIntegrationBuild=true

# =========================
# RUNTIME STAGE
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

# Environment
ENV ASPNETCORE_URLS=http://+:8080 \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    TZ=UTC

EXPOSE 8080

# Publish edilmiş test projesini kopyala
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Vault.Dummy.Web.dll"]
